- name: Install dhcp package
  package:
    name: "{{ dhcp_package  }}"
    state: present
    update_cache: yes

- name: config DHCP server
  template:
    src: dhcp_config.j2
    dest: /etc/dhcp/dhcpd.conf
  notify: restart dhcp service
